# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datawidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_datavis2(object):
    def setupUi(self, datavis2):
        datavis2.setObjectName("datavis2")
        datavis2.resize(400, 300)

        self.retranslateUi(datavis2)
        QtCore.QMetaObject.connectSlotsByName(datavis2)

    def retranslateUi(self, datavis2):
        _translate = QtCore.QCoreApplication.translate
        datavis2.setWindowTitle(_translate("datavis2", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    datavis2 = QtWidgets.QWidget()
    ui = Ui_datavis2()
    ui.setupUi(datavis2)
    datavis2.show()
    sys.exit(app.exec_())
